<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('user_type', function (Blueprint $table) {
            $table->id();
            $table->string('type');
            $table->text('description');
            $table->json('capabilities')->nullable();

        });

        DB::table('user_type')->insert([
            [
                'type' => 'admin',
                'description' => 'Master',
                'capabilities' => json_encode([
                    'clients' => true,
                    'quotes' => true,
                    'orders' => true,
                    'support_quotes' => true,
                    'support_orders' => true,
                    'users' => true,
                    'services' => true,
                    'spares' => true,
                    'shippings' => true,
                    'create_client' => true,
                    'read_client' => true,
                    'update_client' => true,
                    'create_quote' => true,
                    'read_quote' => true,
                    'update_quote'=> true,
                    'delete_quote' => true,
                    'create_order' => true,
                    'read_order' => true,
                    'update_order' => true,
                    'delete_order' => true,
                    'appove_order' => true,
                    'create_support_quote' => true,
                    'read_support_quote' => true,
                    'update_support_quote' => true,
                    'delete_support_quote' => true,
                    'create_support_order' => true,
                    'read_support_order' => true,
                    'update_support_order' => true,
                    'delete_support_order' => true,
                    'approve_support_order' => true,
                    'create_user' => true,
                    'read_user' => true,
                    'update_user' => true,
                    'delete_user' => true,
                    'create_service' => true,
                    'read_service' => true,
                    'update_service' => true,
                    'delete_service' => true,
                    'create_spare' => true,
                    'read_spare' => true,
                    'update_spare' => true,
                    'delete_spare' => true,
                    'create_shipping' => true,
                    'read_shipping' => true,
                    'update_shipping' => true,
                    'delete_shipping' => true,
                ])
            ],
            [
                'type' => 'ceo',
                'description' => 'CEO',
                'capabilities' => json_encode([
                    'clients' => true,
                    'quotes' => true,
                    'orders' => true,
                    'support_quotes' => true,
                    'support_orders' => true,
                    'users' => true,
                    'services' => true,
                    'spares' => true,
                    'shippings' => true,
                    'create_client' => true,
                    'read_client' => true,
                    'update_client' => true,
                    'create_quote' => true,
                    'read_quote' => true,
                    'update_quote'=> true,
                    'delete_quote' => true,
                    'create_order' => true,
                    'read_order' => true,
                    'update_order' => true,
                    'delete_order' => true,
                    'approve_order' => true,
                    'create_support_quote' => true,
                    'read_support_quote' => true,
                    'update_support_quote' => true,
                    'delete_support_quote' => true,
                    'create_support_order' => true,
                    'read_support_order' => true,
                    'update_support_order' => true,
                    'delete_support_order' => true,
                    'approve_support_order' => true,
                    'create_user' => true,
                    'read_user' => true,
                    'update_user' => true,
                    'delete_user' => true,
                    'create_service' => true,
                    'read_service' => true,
                    'update_service' => true,
                    'delete_service' => true,
                    'create_spare' => true,
                    'read_spare' => true,
                    'update_spare' => true,
                    'delete_spare' => true,
                    'create_shipping' => true,
                    'read_shipping' => true,
                    'update_shipping' => true,
                    'delete_shipping' => true,
                ])
            ],
            [
                'type' => 'manager',
                'description' => 'Gerente',
                'capabilities' => json_encode([
                    'clients' => true,
                    'quotes' => true,
                    'orders' => true,
                    'support_quotes' => true,
                    'support_orders' => true,
                    'users' => true,
                    'services' => true,
                    'spares' => true,
                    'shippings' => true,
                    'create_client' => true,
                    'read_client' => true,
                    'update_client' => true,
                    'create_quote' => true,
                    'read_quote' => true,
                    'update_quote'=> true,
                    'delete_quote' => true,
                    'create_order' => true,
                    'read_order' => true,
                    'update_order' => true,
                    'delete_order' => true,
                    'appove_order' => true,
                    'create_support_quote' => true,
                    'read_support_quote' => true,
                    'update_support_quote' => true,
                    'delete_support_quote' => true,
                    'create_support_order' => true,
                    'read_support_order' => true,
                    'update_support_order' => true,
                    'delete_support_order' => true,
                    'approve_support_order' => true,
                    'create_user' => true,
                    'read_user' => true,
                    'update_user' => true,
                    'delete_user' => true,
                    'create_service' => true,
                    'read_service' => true,
                    'update_service' => true,
                    'delete_service' => true,
                    'create_spare' => true,
                    'read_spare' => true,
                    'update_spare' => true,
                    'delete_spare' => true,
                    'create_shipping' => true,
                    'read_shipping' => true,
                    'update_shipping' => true,
                    'delete_shipping' => true,
                ])
            ],
            [
                'type' => 'sub_manager',
                'description' => 'Sub Gerente',
                'capabilities' => json_encode([
                    'clients' => true,
                    'quotes' => true,
                    'orders' => true,
                    'support_quotes' => true,
                    'support_orders' => true,
                    'users' => true,
                    'services' => true,
                    'spares' => true,
                    'shippings' => true,
                    'create_client' => true,
                    'read_client' => true,
                    'update_client' => true,
                    'create_quote' => true,
                    'read_quote' => true,
                    'update_quote'=> true,
                    'delete_quote' => true,
                    'create_order' => true,
                    'read_order' => true,
                    'update_order' => true,
                    'delete_order' => true,
                    'appove_order' => true, 
                    'create_support_quote' => true,
                    'read_support_quote' => true,
                    'update_support_quote' => true,
                    'delete_support_quote' => true,
                    'create_support_order' => true,
                    'read_support_order' => true,
                    'update_support_order' => true,
                    'delete_support_order' => true,
                    'create_user' => true,
                    'read_user' => true,
                    'update_user' => true,
                    'delete_user' => true,
                    'create_service' => true,
                    'read_service' => true,
                    'update_service' => true,
                    'delete_service' => true,
                    'create_spare' => true,
                    'read_spare' => true,
                    'update_spare' => true,
                    'delete_spare' => true,
                    'create_shipping' => true,
                    'read_shipping' => true,
                    'update_shipping' => true,
                    'delete_shipping' => true,

                ])
            ],
            [
                'type' => 'seller',
                'description' => 'Vendedor/a',
                'capabilities' => json_encode([
                    'clients' => true,
                    'quotes' => true,
                    'orders' => true,
                    'support_quotes' => false,
                    'support_orders' => false,
                    'users' => false,
                    'services' => false,
                    'spares' => false,
                    'shippings' => false,
                    'create_client' => true,
                    'read_client' => true,
                    'update_client' => true,
                    'create_quote' => true,
                    'read_quote' => true,
                    'update_quote'=> true,
                    'delete_quote' => true,
                    'create_order' => true,
                    'read_order' => true,
                    'update_order' => false,
                    'delete_order' => false,
                    'appove_order' => false,
                    'create_support_quote' => false,
                    'read_support_quote' => false,
                    'update_support_quote' => false,
                    'delete_support_quote' => false,
                    'create_support_order' => false,
                    'read_support_order' => false,
                    'update_support_order' => false,
                    'delete_support_order' => false,
                    'approve_support_order' => false,
                    'create_user' => false,
                    'read_user' => false,
                    'update_user' => false,
                    'delete_user' => false,
                    'create_service' => false,
                    'read_service' => false,
                    'update_service' => false,
                    'delete_service' => false,
                    'create_spare' => false,
                    'read_spare' => false,
                    'update_spare' => false,
                    'delete_spare' => false,
                    'create_shipping' => false,
                    'read_shipping' => false,
                    'update_shipping' => false,
                    'delete_shipping' => false,
                ])
            ],
            [
                'type' => 'pdv_lider',
                'description' => 'Lider de PDV',
                'capabilities' => json_encode([
                    'clients' => true,
                    'quotes' => true,
                    'orders' => true,
                    'support_quotes' => false,
                    'support_orders' => false,
                    'users' => false,
                    'services' => false,
                    'spares' => false,
                    'shippings' => false,
                    'create_client' => true,
                    'read_client' => true,
                    'update_client' => true,
                    'create_quote' => true,
                    'read_quote' => true,
                    'update_quote'=> true,
                    'delete_quote' => true,
                    'create_order' => true,
                    'read_order' => true,
                    'update_order' => true,
                    'delete_order' => true,
                    'appove_order' => true,
                    'create_support_quote' => false,
                    'read_support_quote' => false,
                    'update_support_quote' => false,
                    'delete_support_quote' => false,
                    'create_support_order' => false,
                    'read_support_order' => false,
                    'update_support_order' => false,
                    'delete_support_order' => false,
                    'approve_support_order' => false,
                    'create_user' => false,
                    'read_user' => false,
                    'update_user' => false,
                    'delete_user' => false,
                    'create_service' => false,
                    'read_service' => false,
                    'update_service' => false,
                    'delete_service' => false,
                    'create_spare' => false,
                    'read_spare' => false,
                    'update_spare' => false,
                    'delete_spare' => false,
                    'create_shipping' => false,
                    'read_shipping' => false,
                    'update_shipping' => false,
                    'delete_shipping' => false,
                ])
            ],
            [
                'type' => 'assitant',
                'description' => 'Asistente de Director',
                'capabilities' => json_encode([
                    'clients' => true,
                    'quotes' => true,
                    'orders' => true,
                    'support_quotes' => true,
                    'support_orders' => true,
                    'users' => false,
                    'services' => true,
                    'spares' => true,
                    'shippings' => true,
                    'create_client' => true,
                    'read_client' => true,
                    'update_client' => true,
                    'create_quote' => true,
                    'read_quote' => true,
                    'update_quote'=> true,
                    'delete_quote' => true,
                    'create_order' => true,
                    'read_order' => true,
                    'update_order' => true,
                    'delete_order' => true,
                    'appove_order' => true,
                    'create_support_quote' => false,
                    'read_support_quote' => true,
                    'update_support_quote' => true,
                    'delete_support_quote' => true,
                    'create_support_order' => false,
                    'read_support_order' => true,
                    'update_support_order' => true,
                    'delete_support_order' => true,
                    'approve_support_order' => true,
                    'create_user' => false,
                    'read_user' => false,
                    'update_user' => false,
                    'delete_user' => false,
                    'create_service' => true,
                    'read_service' => true,
                    'update_service' => true,
                    'delete_service' => true,
                    'create_spare' => true,
                    'read_spare' => true,
                    'update_spare' => true,
                    'delete_spare' => true,
                    'create_shipping' => true,
                    'read_shipping' => true,
                    'update_shipping' => true,
                    'delete_shipping' => true,
                ])
            ],
            [
                'type' => 'accountant',
                'description' => 'Contador',
                'capabilities' => json_encode([
                    'clients' => true,
                    'quotes' => false,
                    'orders' => true,
                    'support_quotes' => false,
                    'support_orders' => true,
                    'users' => false,
                    'services' => true,
                    'spares' => true,
                    'shippings' => true,
                    'create_client' => false,
                    'read_client' => true,
                    'update_client' => false,
                    'create_quote' => false,
                    'read_quote' => false,
                    'update_quote'=> false,
                    'delete_quote' => false,
                    'create_order' => false,
                    'read_order' => true,
                    'update_order' => false,
                    'delete_order' => false,
                    'appove_order' => false,
                    'create_support_quote' => false,
                    'read_support_quote' => true,
                    'update_support_quote' => false,
                    'delete_support_quote' => false,
                    'create_support_order' => false,
                    'read_support_order' => true,
                    'update_support_order' => false,
                    'delete_support_order' => false,
                    'approve_support_order' => false,
                    'create_user' => false,
                    'read_user' => false,
                    'update_user' => false,
                    'delete_user' => false,
                    'create_service' => true,
                    'read_service' => true,
                    'update_service' => true,
                    'delete_service' => true,
                    'create_spare' => true,
                    'read_spare' => true,
                    'update_spare' => true,
                    'delete_spare' => true,
                    'create_shipping' => false,
                    'read_shipping' => false,
                    'update_shipping' => false,
                    'delete_shipping' => false,
                ])
            ],
            [
                'type' => 'repair',
                'description' => 'Servicio Tecnico',
                'capabilities' => json_encode([
                    'clients' => true,
                    'quotes' => false,
                    'orders' => true,
                    'support_quotes' => true,
                    'support_orders' => true,
                    'users' => false,
                    'services' => true,
                    'spares' => true,
                    'shippings' => false,
                    'create_client' => true,
                    'read_client' => true,
                    'update_client' => true,
                    'create_quote' => false,
                    'read_quote' => false,
                    'update_quote'=> false,
                    'delete_quote' => false,
                    'create_order' => false,
                    'read_order' => true,
                    'update_order' => false,
                    'delete_order' => false,
                    'appove_order' => false,
                    'create_support_quote' => true,
                    'read_support_quote' => true,
                    'update_support_quote' => true,
                    'delete_support_quote' => true,
                    'create_support_order' => false,
                    'read_support_order' => true,
                    'update_support_order' => true,
                    'delete_support_order' => true,
                    'approve_support_order' => false,
                    'create_user' => false,
                    'read_user' => false,
                    'update_user' => false,
                    'delete_user' => false,
                    'create_service' => false,
                    'read_service' => true,
                    'update_service' => false,
                    'delete_service' => false,
                    'create_spare' => false,
                    'read_spare' => true,
                    'update_spare' => false,
                    'delete_spare' => false,
                    'create_shipping' => false,
                    'read_shipping' => false,
                    'update_shipping' => false,
                    'delete_shipping' => false,
                ])
            ],
            [
                'type' => 'warehouse',
                'description' => 'Almacen & Envios',
                'capabilities' => json_encode([
                    'clients' => true,
                    'quotes' => false,
                    'orders' => true,
                    'support_quotes' => false,
                    'support_orders' => true,
                    'users' => false,
                    'services' => false,
                    'spares' => false,
                    'shippings' => true,
                    'create_client' => false,
                    'read_client' => true,
                    'update_client' => false,
                    'create_quote' => false,
                    'read_quote' => false,
                    'update_quote'=> false,
                    'delete_quote' => false,
                    'create_order' => false,
                    'read_order' => true,
                    'update_order' => false,
                    'delete_order' => false,
                    'appove_order' => false,
                    'create_support_quote' => false,
                    'read_support_quote' => false,
                    'update_support_quote' => false,
                    'delete_support_quote' => false,
                    'create_support_order' => false,
                    'read_support_order' => true,
                    'update_support_order' => false,
                    'delete_support_order' => false,
                    'approve_support_order' => false,
                    'create_user' => false,
                    'read_user' => false,
                    'update_user' => false,
                    'delete_user' => false,
                    'create_service' => false,
                    'read_service' => false,
                    'update_service' => false,
                    'delete_service' => false,
                    'create_spare' => false,
                    'read_spare' => false,
                    'update_spare' => false,
                    'delete_spare' => false,
                    'create_shipping' => true,
                    'read_shipping' => true,
                    'update_shipping' => true,
                    'delete_shipping' => true,
                ])
            ]
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('user_type');
    }
};
